# Dapper configuration file
---
name: Postcircumfix
subtitle: A Perl 6 blog by smls
category: Perl 6
url: http://postcircumfix.com
themecolor: '#2b2a25'
permanent_domain: postcircumfix.com
urlpattern: /:year-:month-:day-:slug
author:
    name:  smls
    email: smls@postcircumfix.com
    url:   http://smls.tk
navlinks:
    archive: /archive
    feed:    /feed
ignore :
    - "^\."
    - "^_"
    - "^.*/_"
    - "^favicons$"
    - "^README.md$"
    - "^Makefile$"
revisions:
    /style/site.css: 2
