# Dapper configuration file
---
name: Postcircumfix
subtitle: A Perl 6 blog by smls
category: Perl 6
url: http://postcircumfix.com
permanent_domain: postcircumfix.com
urlpattern: /:year-:month-:day-:slug
author:
    name:  smls
    email: smls@postcircumfix.com
    url:   http://smls.tk
navlinks:
    archive: /archive
    feed:    /feed
ignore :
    - "^\."
    - "^_"
    - "^design$"
    - "^README.md$"
    - "^Makefile$"
