# Dapper configuration file
---
name: Postcircumfix
url: http://postcircumfix.com/
source : _source/
output : _output/
layout : _layout/
ignore :
    - "^\."
    - "^_"
    - "^design$"
    - "^README.md$"
    - "^Makefile$"
